/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AwarenessTip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'category' : string,
}
export interface ContactInquiry {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'mode' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'isActive' : boolean,
  'capacity' : bigint,
  'location' : string,
  'eventType' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'createAwarenessTip' : ActorMethod<[string, string, string], bigint>,
  'createCourse' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    bigint
  >,
  'createEvent' : ActorMethod<
    [string, string, Time, string, string, bigint],
    bigint
  >,
  'deleteAwarenessTip' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllTips' : ActorMethod<[], Array<AwarenessTip>>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  'getInquiries' : ActorMethod<[Principal], Array<ContactInquiry>>,
  'getTip' : ActorMethod<[bigint], [] | [AwarenessTip]>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateAwarenessTip' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateCourse' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, string, boolean],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [bigint, string, string, Time, string, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];